version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      python-patches:
        update-types:
          - "version-update:patch"
      python-minors:
        update-types:
          - "version-update:minor"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      npm-patches:
        update-types:
          - "version-update:patch"
      npm-minors:
        update-types:
          - "version-update:minor"
