services:
  postgres:
    image: docker.io/library/postgres:15
    container_name: phx-postgres
    environment:
      POSTGRES_USER: phxuser
      POSTGRES_PASSWORD: phxpw
      POSTGRES_DB: phxdb
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phxuser -d phxdb"]
      interval: 5s
      timeout: 5s
      retries: 5

